### PR TITLE
Don't assume GCC/Clang compiler

### PR DESCRIPTION
**Pull request by NewProggie**

### CODE REVIEW

**Comment by NewProggie** [comment]
Also,

if you really want to gain full flexibility, you should consider exporting all of your targets into a package to be able to use your project from the build tree, so clients don't have to install it first, if they use it as another dependency. For instance:

    # Export the package for use from the build tree
    export(TARGETS jsonutils NAMESPACE JSONUtils:: cmake/JSONUtilsTargets.cmake)
    export(PACKAGE jsonutils)

**Comment by mathstuf** [comment]
Eh, `export(PACKAGE)` is (IMO) annoying. Personally, I symlink `$HOME/.cmake` to `/dev/null` to avoid it since it doesn't handle multiple build trees for a single project well. It should probably be guarded by an option that can be disabled.

**Comment by pabloariasal** [comment]
@NewProggie I do export the targets from the build tree, look at the bottom of the `CMakeListst.txt`
```
export(EXPORT jsonutils-targets FILE ${CMAKE_CURRENT_BINARY_DIR}/JSONUtilsTargets.cmake NAMESPACE JSONUtils::)
#Register package in user's package registry
export(PACKAGE JSONUtils)
```
I actually find the package registry very useful.

**Comment by pabloariasal** [comment]
Thank you for the pull request! As far I know, the `-Wall` option is is supported by all compilers or am I wrong? Are you sure that that generator expression is required in this particular scenario?

**Comment by NewProggie** [comment]
@pabloariasal Unfortunately, this is not the case. First, when compiling on Windows (using VS), MSVC expects compiler flags to be in the format `/<flag>`. If a simple dash works in your case, then you're relying on CMake to be able to parse sloppy compiler flags.

Also, I believe that the TI compiler had problems with this flag. The same holds true for the Panasonic one and many other embedded or otherwise proprietary compiler you're not even aware of. There are almost as many compilers out there as there are software projects and not just clang, gcc, msvc or icc :-)

You're right concerning the `export(PACKAGE)` command. I must have overlooked this. Otherwise good job 👍

**Comment by pabloariasal** [comment]
Alright Kai, thank you! Merged.

**Comment by mathstuf** [comment]
@pabloariasal I'm not doubting it is useful to some people, but an option to avoid it would be nice.

**Comment by mathstuf** [comment]
Actually, I see there is the `CMAKE_EXPORT_NO_PACKAGE_REGISTRY` variable which already handles it nicely.

**Comment by pabloariasal** [comment]
Interesting. It's solved then :)

**Pull request merged**
